/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "network_constants.h"

namespace genbridge {

const networkConstants g_network_constants;

networkConstants::networkConstants() {
}

} // namespace

