/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package genbridge;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ProgressAxisData implements org.apache.thrift.TBase<ProgressAxisData, ProgressAxisData._Fields>, java.io.Serializable, Cloneable, Comparable<ProgressAxisData> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ProgressAxisData");

  private static final org.apache.thrift.protocol.TField PROGRESS_BASE1_FIELD_DESC = new org.apache.thrift.protocol.TField("progressBase1", org.apache.thrift.protocol.TType.DOUBLE, (short)1);
  private static final org.apache.thrift.protocol.TField PROGRESS_BASE2_FIELD_DESC = new org.apache.thrift.protocol.TField("progressBase2", org.apache.thrift.protocol.TType.DOUBLE, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ProgressAxisDataStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ProgressAxisDataTupleSchemeFactory());
  }

  public double progressBase1; // required
  public double progressBase2; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PROGRESS_BASE1((short)1, "progressBase1"),
    PROGRESS_BASE2((short)2, "progressBase2");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PROGRESS_BASE1
          return PROGRESS_BASE1;
        case 2: // PROGRESS_BASE2
          return PROGRESS_BASE2;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PROGRESSBASE1_ISSET_ID = 0;
  private static final int __PROGRESSBASE2_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PROGRESS_BASE1, new org.apache.thrift.meta_data.FieldMetaData("progressBase1", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.PROGRESS_BASE2, new org.apache.thrift.meta_data.FieldMetaData("progressBase2", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ProgressAxisData.class, metaDataMap);
  }

  public ProgressAxisData() {
  }

  public ProgressAxisData(
    double progressBase1,
    double progressBase2)
  {
    this();
    this.progressBase1 = progressBase1;
    setProgressBase1IsSet(true);
    this.progressBase2 = progressBase2;
    setProgressBase2IsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ProgressAxisData(ProgressAxisData other) {
    __isset_bitfield = other.__isset_bitfield;
    this.progressBase1 = other.progressBase1;
    this.progressBase2 = other.progressBase2;
  }

  public ProgressAxisData deepCopy() {
    return new ProgressAxisData(this);
  }

  @Override
  public void clear() {
    setProgressBase1IsSet(false);
    this.progressBase1 = 0.0;
    setProgressBase2IsSet(false);
    this.progressBase2 = 0.0;
  }

  public double getProgressBase1() {
    return this.progressBase1;
  }

  public ProgressAxisData setProgressBase1(double progressBase1) {
    this.progressBase1 = progressBase1;
    setProgressBase1IsSet(true);
    return this;
  }

  public void unsetProgressBase1() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PROGRESSBASE1_ISSET_ID);
  }

  /** Returns true if field progressBase1 is set (has been assigned a value) and false otherwise */
  public boolean isSetProgressBase1() {
    return EncodingUtils.testBit(__isset_bitfield, __PROGRESSBASE1_ISSET_ID);
  }

  public void setProgressBase1IsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PROGRESSBASE1_ISSET_ID, value);
  }

  public double getProgressBase2() {
    return this.progressBase2;
  }

  public ProgressAxisData setProgressBase2(double progressBase2) {
    this.progressBase2 = progressBase2;
    setProgressBase2IsSet(true);
    return this;
  }

  public void unsetProgressBase2() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PROGRESSBASE2_ISSET_ID);
  }

  /** Returns true if field progressBase2 is set (has been assigned a value) and false otherwise */
  public boolean isSetProgressBase2() {
    return EncodingUtils.testBit(__isset_bitfield, __PROGRESSBASE2_ISSET_ID);
  }

  public void setProgressBase2IsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PROGRESSBASE2_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PROGRESS_BASE1:
      if (value == null) {
        unsetProgressBase1();
      } else {
        setProgressBase1((Double)value);
      }
      break;

    case PROGRESS_BASE2:
      if (value == null) {
        unsetProgressBase2();
      } else {
        setProgressBase2((Double)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PROGRESS_BASE1:
      return Double.valueOf(getProgressBase1());

    case PROGRESS_BASE2:
      return Double.valueOf(getProgressBase2());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PROGRESS_BASE1:
      return isSetProgressBase1();
    case PROGRESS_BASE2:
      return isSetProgressBase2();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ProgressAxisData)
      return this.equals((ProgressAxisData)that);
    return false;
  }

  public boolean equals(ProgressAxisData that) {
    if (that == null)
      return false;

    boolean this_present_progressBase1 = true;
    boolean that_present_progressBase1 = true;
    if (this_present_progressBase1 || that_present_progressBase1) {
      if (!(this_present_progressBase1 && that_present_progressBase1))
        return false;
      if (this.progressBase1 != that.progressBase1)
        return false;
    }

    boolean this_present_progressBase2 = true;
    boolean that_present_progressBase2 = true;
    if (this_present_progressBase2 || that_present_progressBase2) {
      if (!(this_present_progressBase2 && that_present_progressBase2))
        return false;
      if (this.progressBase2 != that.progressBase2)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(ProgressAxisData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetProgressBase1()).compareTo(other.isSetProgressBase1());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProgressBase1()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.progressBase1, other.progressBase1);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetProgressBase2()).compareTo(other.isSetProgressBase2());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProgressBase2()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.progressBase2, other.progressBase2);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ProgressAxisData(");
    boolean first = true;

    sb.append("progressBase1:");
    sb.append(this.progressBase1);
    first = false;
    if (!first) sb.append(", ");
    sb.append("progressBase2:");
    sb.append(this.progressBase2);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ProgressAxisDataStandardSchemeFactory implements SchemeFactory {
    public ProgressAxisDataStandardScheme getScheme() {
      return new ProgressAxisDataStandardScheme();
    }
  }

  private static class ProgressAxisDataStandardScheme extends StandardScheme<ProgressAxisData> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ProgressAxisData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PROGRESS_BASE1
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.progressBase1 = iprot.readDouble();
              struct.setProgressBase1IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PROGRESS_BASE2
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.progressBase2 = iprot.readDouble();
              struct.setProgressBase2IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ProgressAxisData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(PROGRESS_BASE1_FIELD_DESC);
      oprot.writeDouble(struct.progressBase1);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(PROGRESS_BASE2_FIELD_DESC);
      oprot.writeDouble(struct.progressBase2);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ProgressAxisDataTupleSchemeFactory implements SchemeFactory {
    public ProgressAxisDataTupleScheme getScheme() {
      return new ProgressAxisDataTupleScheme();
    }
  }

  private static class ProgressAxisDataTupleScheme extends TupleScheme<ProgressAxisData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ProgressAxisData struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetProgressBase1()) {
        optionals.set(0);
      }
      if (struct.isSetProgressBase2()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetProgressBase1()) {
        oprot.writeDouble(struct.progressBase1);
      }
      if (struct.isSetProgressBase2()) {
        oprot.writeDouble(struct.progressBase2);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ProgressAxisData struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.progressBase1 = iprot.readDouble();
        struct.setProgressBase1IsSet(true);
      }
      if (incoming.get(1)) {
        struct.progressBase2 = iprot.readDouble();
        struct.setProgressBase2IsSet(true);
      }
    }
  }

}

