/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package genbridge;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ProgressAxisInitData implements org.apache.thrift.TBase<ProgressAxisInitData, ProgressAxisInitData._Fields>, java.io.Serializable, Cloneable, Comparable<ProgressAxisInitData> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ProgressAxisInitData");

  private static final org.apache.thrift.protocol.TField BASE1_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("base1_id", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField BASE2_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("base2_id", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ProgressAxisInitDataStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ProgressAxisInitDataTupleSchemeFactory());
  }

  public int base1_id; // required
  public int base2_id; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    BASE1_ID((short)1, "base1_id"),
    BASE2_ID((short)2, "base2_id");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // BASE1_ID
          return BASE1_ID;
        case 2: // BASE2_ID
          return BASE2_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __BASE1_ID_ISSET_ID = 0;
  private static final int __BASE2_ID_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BASE1_ID, new org.apache.thrift.meta_data.FieldMetaData("base1_id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    tmpMap.put(_Fields.BASE2_ID, new org.apache.thrift.meta_data.FieldMetaData("base2_id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ProgressAxisInitData.class, metaDataMap);
  }

  public ProgressAxisInitData() {
  }

  public ProgressAxisInitData(
    int base1_id,
    int base2_id)
  {
    this();
    this.base1_id = base1_id;
    setBase1_idIsSet(true);
    this.base2_id = base2_id;
    setBase2_idIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ProgressAxisInitData(ProgressAxisInitData other) {
    __isset_bitfield = other.__isset_bitfield;
    this.base1_id = other.base1_id;
    this.base2_id = other.base2_id;
  }

  public ProgressAxisInitData deepCopy() {
    return new ProgressAxisInitData(this);
  }

  @Override
  public void clear() {
    setBase1_idIsSet(false);
    this.base1_id = 0;
    setBase2_idIsSet(false);
    this.base2_id = 0;
  }

  public int getBase1_id() {
    return this.base1_id;
  }

  public ProgressAxisInitData setBase1_id(int base1_id) {
    this.base1_id = base1_id;
    setBase1_idIsSet(true);
    return this;
  }

  public void unsetBase1_id() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __BASE1_ID_ISSET_ID);
  }

  /** Returns true if field base1_id is set (has been assigned a value) and false otherwise */
  public boolean isSetBase1_id() {
    return EncodingUtils.testBit(__isset_bitfield, __BASE1_ID_ISSET_ID);
  }

  public void setBase1_idIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __BASE1_ID_ISSET_ID, value);
  }

  public int getBase2_id() {
    return this.base2_id;
  }

  public ProgressAxisInitData setBase2_id(int base2_id) {
    this.base2_id = base2_id;
    setBase2_idIsSet(true);
    return this;
  }

  public void unsetBase2_id() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __BASE2_ID_ISSET_ID);
  }

  /** Returns true if field base2_id is set (has been assigned a value) and false otherwise */
  public boolean isSetBase2_id() {
    return EncodingUtils.testBit(__isset_bitfield, __BASE2_ID_ISSET_ID);
  }

  public void setBase2_idIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __BASE2_ID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case BASE1_ID:
      if (value == null) {
        unsetBase1_id();
      } else {
        setBase1_id((Integer)value);
      }
      break;

    case BASE2_ID:
      if (value == null) {
        unsetBase2_id();
      } else {
        setBase2_id((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case BASE1_ID:
      return Integer.valueOf(getBase1_id());

    case BASE2_ID:
      return Integer.valueOf(getBase2_id());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case BASE1_ID:
      return isSetBase1_id();
    case BASE2_ID:
      return isSetBase2_id();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ProgressAxisInitData)
      return this.equals((ProgressAxisInitData)that);
    return false;
  }

  public boolean equals(ProgressAxisInitData that) {
    if (that == null)
      return false;

    boolean this_present_base1_id = true;
    boolean that_present_base1_id = true;
    if (this_present_base1_id || that_present_base1_id) {
      if (!(this_present_base1_id && that_present_base1_id))
        return false;
      if (this.base1_id != that.base1_id)
        return false;
    }

    boolean this_present_base2_id = true;
    boolean that_present_base2_id = true;
    if (this_present_base2_id || that_present_base2_id) {
      if (!(this_present_base2_id && that_present_base2_id))
        return false;
      if (this.base2_id != that.base2_id)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(ProgressAxisInitData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetBase1_id()).compareTo(other.isSetBase1_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBase1_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.base1_id, other.base1_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBase2_id()).compareTo(other.isSetBase2_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBase2_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.base2_id, other.base2_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ProgressAxisInitData(");
    boolean first = true;

    sb.append("base1_id:");
    sb.append(this.base1_id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("base2_id:");
    sb.append(this.base2_id);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ProgressAxisInitDataStandardSchemeFactory implements SchemeFactory {
    public ProgressAxisInitDataStandardScheme getScheme() {
      return new ProgressAxisInitDataStandardScheme();
    }
  }

  private static class ProgressAxisInitDataStandardScheme extends StandardScheme<ProgressAxisInitData> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ProgressAxisInitData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // BASE1_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.base1_id = iprot.readI32();
              struct.setBase1_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // BASE2_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.base2_id = iprot.readI32();
              struct.setBase2_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ProgressAxisInitData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(BASE1_ID_FIELD_DESC);
      oprot.writeI32(struct.base1_id);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(BASE2_ID_FIELD_DESC);
      oprot.writeI32(struct.base2_id);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ProgressAxisInitDataTupleSchemeFactory implements SchemeFactory {
    public ProgressAxisInitDataTupleScheme getScheme() {
      return new ProgressAxisInitDataTupleScheme();
    }
  }

  private static class ProgressAxisInitDataTupleScheme extends TupleScheme<ProgressAxisInitData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ProgressAxisInitData struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetBase1_id()) {
        optionals.set(0);
      }
      if (struct.isSetBase2_id()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetBase1_id()) {
        oprot.writeI32(struct.base1_id);
      }
      if (struct.isSetBase2_id()) {
        oprot.writeI32(struct.base2_id);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ProgressAxisInitData struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.base1_id = iprot.readI32();
        struct.setBase1_idIsSet(true);
      }
      if (incoming.get(1)) {
        struct.base2_id = iprot.readI32();
        struct.setBase2_idIsSet(true);
      }
    }
  }

}

