/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package genbridge;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TakeOffCommandData implements org.apache.thrift.TBase<TakeOffCommandData, TakeOffCommandData._Fields>, java.io.Serializable, Cloneable, Comparable<TakeOffCommandData> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TakeOffCommandData");

  private static final org.apache.thrift.protocol.TField PC_FIELD_DESC = new org.apache.thrift.protocol.TField("pc", org.apache.thrift.protocol.TType.STRUCT, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TakeOffCommandDataStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TakeOffCommandDataTupleSchemeFactory());
  }

  public PlaneCommandData pc; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PC((short)1, "pc");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PC
          return PC;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PC, new org.apache.thrift.meta_data.FieldMetaData("pc", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, PlaneCommandData.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TakeOffCommandData.class, metaDataMap);
  }

  public TakeOffCommandData() {
  }

  public TakeOffCommandData(
    PlaneCommandData pc)
  {
    this();
    this.pc = pc;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TakeOffCommandData(TakeOffCommandData other) {
    if (other.isSetPc()) {
      this.pc = new PlaneCommandData(other.pc);
    }
  }

  public TakeOffCommandData deepCopy() {
    return new TakeOffCommandData(this);
  }

  @Override
  public void clear() {
    this.pc = null;
  }

  public PlaneCommandData getPc() {
    return this.pc;
  }

  public TakeOffCommandData setPc(PlaneCommandData pc) {
    this.pc = pc;
    return this;
  }

  public void unsetPc() {
    this.pc = null;
  }

  /** Returns true if field pc is set (has been assigned a value) and false otherwise */
  public boolean isSetPc() {
    return this.pc != null;
  }

  public void setPcIsSet(boolean value) {
    if (!value) {
      this.pc = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PC:
      if (value == null) {
        unsetPc();
      } else {
        setPc((PlaneCommandData)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PC:
      return getPc();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PC:
      return isSetPc();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TakeOffCommandData)
      return this.equals((TakeOffCommandData)that);
    return false;
  }

  public boolean equals(TakeOffCommandData that) {
    if (that == null)
      return false;

    boolean this_present_pc = true && this.isSetPc();
    boolean that_present_pc = true && that.isSetPc();
    if (this_present_pc || that_present_pc) {
      if (!(this_present_pc && that_present_pc))
        return false;
      if (!this.pc.equals(that.pc))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(TakeOffCommandData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPc()).compareTo(other.isSetPc());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPc()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pc, other.pc);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TakeOffCommandData(");
    boolean first = true;

    sb.append("pc:");
    if (this.pc == null) {
      sb.append("null");
    } else {
      sb.append(this.pc);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (pc != null) {
      pc.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TakeOffCommandDataStandardSchemeFactory implements SchemeFactory {
    public TakeOffCommandDataStandardScheme getScheme() {
      return new TakeOffCommandDataStandardScheme();
    }
  }

  private static class TakeOffCommandDataStandardScheme extends StandardScheme<TakeOffCommandData> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TakeOffCommandData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PC
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.pc = new PlaneCommandData();
              struct.pc.read(iprot);
              struct.setPcIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TakeOffCommandData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.pc != null) {
        oprot.writeFieldBegin(PC_FIELD_DESC);
        struct.pc.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TakeOffCommandDataTupleSchemeFactory implements SchemeFactory {
    public TakeOffCommandDataTupleScheme getScheme() {
      return new TakeOffCommandDataTupleScheme();
    }
  }

  private static class TakeOffCommandDataTupleScheme extends TupleScheme<TakeOffCommandData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TakeOffCommandData struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPc()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetPc()) {
        struct.pc.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TakeOffCommandData struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.pc = new PlaneCommandData();
        struct.pc.read(iprot);
        struct.setPcIsSet(true);
      }
    }
  }

}

